// -----------------------------------------------------------------------
// Darie-Dragos Mitoiu
// TwitStips (postConstants.js) v1.0.0 11/07/2022
// A web application designed for a personal website
// -----------------------------------------------------------------------

// Declaring constants
const POST_REQUEST = "POST_REQUEST";
const POST_SUCCESS = "POST_SUCCESS";
const POST_FAIL = "POST_FAIL";

const POST_DATA_REQUEST = "POST_DATA_REQUEST";
const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
const POST_DATA_FAIL = "POST_DATA_FAIL";

const POST_DATA_CONTENT_REQUEST = "POST_DATA_CONTENT_REQUEST";
const POST_DATA_CONTENT_SUCCESS = "POST_DATA_CONTENT_SUCCESS";
const POST_DATA_CONTENT_FAIL = "POST_DATA_CONTENT_FAIL";

const POST_ADD_REQUEST = "POST_ADD_REQUEST";
const POST_ADD_SUCCESS = "POST_ADD_SUCCESS";
const POST_ADD_FAIL = "POST_ADD_FAIL";

const POST_UPDATE_REQUEST = "POST_DELETE_REQUEST";
const POST_UPDATE_SUCCESS = "POST_DELETE_SUCCESS";
const POST_UPDATE_FAIL = "POST_DELETE_FAIL";

const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export {POST_REQUEST, POST_SUCCESS, POST_FAIL,
    POST_DATA_CONTENT_REQUEST, POST_DATA_CONTENT_SUCCESS, POST_DATA_CONTENT_FAIL,
    POST_DATA_REQUEST, POST_DATA_SUCCESS, POST_DATA_FAIL,
    POST_ADD_REQUEST, POST_ADD_SUCCESS, POST_ADD_FAIL,
    POST_UPDATE_REQUEST, POST_UPDATE_SUCCESS, POST_UPDATE_FAIL,
    POST_DELETE_REQUEST, POST_DELETE_SUCCESS, POST_DELETE_FAIL}